import logging
import random
import pygame

from MetaMindIQTrain.core.scalingHelper import ScalingHelper
from MetaMindIQTrain.core.theme import Theme, ThemeProvider
from MetaMindIQTrain.trainingModule import TrainingModule


class ThemeAwareExpandVision(TrainingModule):
    """
    ThemeAwareExpandVision implements a peripheral vision training module that adapts UI elements
    based on the current theme and screen resolution. It uses a ScalingHelper for dynamic layout
    adjustments and a ThemeProvider to apply consistent styling, ensuring a uniform experience across
    different platforms (pygame and web equivalents).
    """
    def __init__(self, themeProvider: ThemeProvider, screen: pygame.Surface):
        super().__init__()
        self.themeProvider = themeProvider
        self.screen = screen
        self.scalingHelper = ScalingHelper(screen.get_size())
        self.logger = logging.getLogger(__name__)
        
        # Initialize UI related properties
        self.center = (screen.get_width() // 2, screen.get_height() // 2)
        self.expandingCircleRadius = self.scalingHelper.scaleValue(50)
        self.currentPhase = 'initial'
        self.numbers = []
        self.feedback = ''
        self.timer = 0

    def buildUI(self):
        """
        Construct the UI components using the current theme styles and resolution scaling.
        """
        currentTheme = self.themeProvider.getTheme()
        containerStyle = currentTheme.getStyle('expandVision.container')
        fieldStyle = currentTheme.getStyle('expandVision.field')

        # Draw container background
        pygame.draw.rect(self.screen, containerStyle.get('backgroundColor', (0, 0, 0)), self.screen.get_rect())
        
        # Draw an expanding circle to represent dynamic field element
        pygame.draw.circle(
            self.screen,
            fieldStyle.get('accentColor', (255, 0, 0)),
            self.center,
            int(self.expandingCircleRadius)
        )

    def update(self, dt: float):
        """
        Update the module state, including animations and internal timers.
        """
        self.timer += dt
        # Update expanding circle radius to create an animation effect
        self.expandingCircleRadius += dt * 10  # speed factor can be adjusted
        if self.expandingCircleRadius > self.screen.get_width() // 2:
            self.expandingCircleRadius = self.scalingHelper.scaleValue(50)
        
        self.buildUI()

    def handleInteraction(self, event: pygame.event.Event):
        """
        Process user interactions, such as mouse clicks, which may alter the module state.
        """
        if event.type == pygame.MOUSEBUTTONDOWN:
            self.logger.info('Mouse click detected; resetting timer and providing feedback.')
            self.timer = 0
            self.feedback = 'Clicked!'

    def getFeedback(self) -> str:
        """
        Retrieve any feedback generated by the module.
        """
        return self.feedback


if __name__ == '__main__':
    # Standalone test for ThemeAwareExpandVision module
    pygame.init()
    screen = pygame.display.set_mode((800, 600))
    
    # For testing, create a simple dark theme instance
    simpleDarkTheme = Theme.createDarkTheme()
    themeProvider = ThemeProvider(simpleDarkTheme)
    
    module = ThemeAwareExpandVision(themeProvider, screen)
    clock = pygame.time.Clock()
    running = True
    
    while running:
        dt = clock.tick(60) / 1000.0
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False
            module.handleInteraction(event)
        
        module.update(dt)
        pygame.display.flip()
        
    pygame.quit() 